start c:\python27\python.exe server.py
timeout /t 2
start c:\python27\python.exe client_observer.py
timeout /t 2
start c:\python27\python.exe AI_deliberate.py
timeout /t 2
start c:\python27\python.exe AI_randomwalk.py
timeout /t 2
start c:\python27\python.exe AI_randomwalk.py
